### ISSUE TITLE
Where can I find stadis-linux-amd64.zip?

### ISSUE THREAD

**Issue by harryge00** [minyk/dcos-commons#1]
Hi, Drake, thanks for your great work in this redis framework. I was building this framework but found a problem: 
https://github.com/minyk/dcos-redis/blob/redis/frameworks/redis/universe/resource.json#L9 use a stadis-linux-amd64.zip, but I cannot find it anywhere. How can I download this `stadis-linux-amd64.zip`?

Thanks

**Comment by harryge00** [comment]
https://github.com/feelobot/stadis/releases/download/v0.0.2/stadis-linux-amd64

I found it!

**Comment by minyk** [comment]
@harryge00 If you using DC/OS 2.X, then you should upgrade the DC/OS SDK version. See this: https://github.com/mesosphere/dcos-commons/pull/3215

**Comment by kaiwalyajoshi** [comment]
correct, highy recommend updating to SDK [v0.57.3](https://github.com/mesosphere/dcos-commons/releases/tag/0.57.3) as it has a critical uninstall fix for quota roles for DC/OS 2.x and above.
